In [32]:
from tensorflow.keras.preprocessing.text import one_hot

In [33]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [35]:
## Define the vocabulary size
voc_size=10000

In [36]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [37]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5962, 620, 6073, 2073],
 [5962, 620, 6073, 7592],
 [5962, 5596, 6073, 20],
 [5875, 5879, 4535, 240, 6049],
 [5875, 5879, 4535, 240, 9374],
 [6490, 5962, 8245, 6073, 7798],
 [2809, 6983, 670, 240]]

In [38]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [39]:
import numpy as np

In [40]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5962  620 6073 2073]
 [   0    0    0    0 5962  620 6073 7592]
 [   0    0    0    0 5962 5596 6073   20]
 [   0    0    0 5875 5879 4535  240 6049]
 [   0    0    0 5875 5879 4535  240 9374]
 [   0    0    0 6490 5962 8245 6073 7798]
 [   0    0    0    0 2809 6983  670  240]]


In [41]:
## feature representation
dim=10

In [42]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Gen_AI\AI_Core\DL_ANN_Project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [43]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [ 0.01133987,  0.04079688, -0.03527042, -0.0381164 ,
          0.00307376,  0.0193969 ,  0.03544908, -0.01748157,
         -0.03973175, -0.02303964],
        [ 0.04476622,  0.00435882, -0.01974114, -0.02310219,
         -0.01107675, -0.0404355 ,  0.00650461,  0.00451015,
          0.00128057, -0.02584122],
        [ 0.0392717 ,  0.01091455,  0.04941256, -0.0

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 5962,  620, 6073, 2073], dtype=int32)

In [47]:
model.predict(embedded_docs[0].reshape(1, -1)) 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[[-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [ 0.01133987,  0.04079688, -0.03527042, -0.0381164 ,
          0.00307376,  0.0193969 ,  0.03544908, -0.01748157,
         -0.03973175, -0.02303964],
        [ 0.04476622,  0.00435882, -0.01974114, -0.02310219,
         -0.01107675, -0.0404355 ,  0.00650461,  0.00451015,
          0.00128057, -0.02584122],
        [ 0.0392717 ,  0.01091455,  0.04941256, -0.0

In [48]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[[-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [-0.04947148, -0.03008687, -0.03878685, -0.03890177,
         -0.0462421 , -0.00102703,  0.03480437, -0.03563849,
          0.01985934, -0.04462348],
        [ 0.01133987,  0.04079688, -0.03527042, -0.0381164 ,
          0.00307376,  0.0193969 ,  0.03544908, -0.01748157,
         -0.03973175, -0.02303964],
        [ 0.04476622,  0.00435882, -0.01974114, -0.02310219,
         -0.01107675, -0.0404355 ,  0.00650461,  0.00451015,
          0.00128057, -0.02584122],
        [ 0.0392717 ,  0.01091455,  0.04941256, -0.0